name: CI

on:
  workflow_dispatch:
    inputs:
    
      instance:
        default: d1
        required: True
        type: choice
        description: Select the instance
        options:
        - d1
        - s1
        - p1
        - test
      
      boolean:
        
        type: boolean
        description: -data_5K
      boolan:
        type: boolean
        description: -data_10k
      boo:
        type: boolean
        description: -data_15k
        
        
        

        
        
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Runs a single command using the runners shell

    - name: Send greeting
      
      run: |
        echo "Hello ${{ github.event.inputs.instance}}" / ${{ inputs.instance }}
        echo "boo is ${{ github.event.inputs.boolean }}" / ${{ inputs.boo }} 
        
         
          
