name: CI

on:
  workflow_dispatch:
    inputs:
    
      choice:
        default: adi-d1
        required: true
        type: list
        description: Select the Environment
        options:
        - adi-d1
        - adi-s1
        - adi-p1
      boolean:
        type: boolean
        description: -data_5K
      boolan:
        type: boolean
        description: -data_10k
      boo:
        type: boolean
        description: -data_15k
        
        
        

        
        
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Runs a single command using the runners shell

    - name: Send greeting
      
      run: |
        echo "Hello ${{ github.event.inputs.choice }}"
        echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
        
         
          
