name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        default: adi-d1
        required: true
        type: list
        description: Select the Environment
        options:
        - adi-d1
        - adi-s1
        - adi-p1
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Token'
        # Default value if no value is explicitly provided
        
        # Input has to be provided for the workflow to run
        required: true
      
        
        
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Runs a single command using the runners shell

    - name: Send greeting

      run: echo "Hello ${{ github.event.inputs.name }}"
          
